package de.adfprojectsesions.hf.model.adfbc.views;

import de.adfprojectsesions.hf.model.adfbc.views.common.HfPlaylistPosViewRow;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 22 21:44:58 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HfPlaylistPosViewRowImpl extends ViewRowImpl implements HfPlaylistPosViewRow {

    public static final int ENTITY_HFPLAYLISTPOS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IntKey,
        HfPlaylistIk,
        OrderNum,
        IntSeq,
        LastChange,
        TrackName,
        Album,
        Artist,
        ArtistId,
        AlbumId,
        TrackId,
        Genre,
        ImageUrl;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int INTKEY = AttributesEnum.IntKey.index();
    public static final int HFPLAYLISTIK = AttributesEnum.HfPlaylistIk.index();
    public static final int ORDERNUM = AttributesEnum.OrderNum.index();
    public static final int INTSEQ = AttributesEnum.IntSeq.index();
    public static final int LASTCHANGE = AttributesEnum.LastChange.index();
    public static final int TRACKNAME = AttributesEnum.TrackName.index();
    public static final int ALBUM = AttributesEnum.Album.index();
    public static final int ARTIST = AttributesEnum.Artist.index();
    public static final int ARTISTID = AttributesEnum.ArtistId.index();
    public static final int ALBUMID = AttributesEnum.AlbumId.index();
    public static final int TRACKID = AttributesEnum.TrackId.index();
    public static final int GENRE = AttributesEnum.Genre.index();
    public static final int IMAGEURL = AttributesEnum.ImageUrl.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HfPlaylistPosViewRowImpl() {
    }

    /**
     * Gets HfPlaylistPos entity object.
     * @return the HfPlaylistPos
     */
    public EntityImpl getHfPlaylistPos() {
        return (EntityImpl) getEntity(ENTITY_HFPLAYLISTPOS);
    }

    /**
     * Gets the attribute value for INT_KEY using the alias name IntKey.
     * @return the INT_KEY
     */
    public Long getIntKey() {
        return (Long) getAttributeInternal(INTKEY);
    }

    /**
     * Sets <code>value</code> as attribute value for INT_KEY using the alias name IntKey.
     * @param value value to set the INT_KEY
     */
    public void setIntKey(Long value) {
        setAttributeInternal(INTKEY, value);
    }

    /**
     * Gets the attribute value for HF_PLAYLIST_IK using the alias name HfPlaylistIk.
     * @return the HF_PLAYLIST_IK
     */
    public Long getHfPlaylistIk() {
        return (Long) getAttributeInternal(HFPLAYLISTIK);
    }

    /**
     * Sets <code>value</code> as attribute value for HF_PLAYLIST_IK using the alias name HfPlaylistIk.
     * @param value value to set the HF_PLAYLIST_IK
     */
    public void setHfPlaylistIk(Long value) {
        setAttributeInternal(HFPLAYLISTIK, value);
    }

    /**
     * Gets the attribute value for ORDER_NUM using the alias name OrderNum.
     * @return the ORDER_NUM
     */
    public Integer getOrderNum() {
        return (Integer) getAttributeInternal(ORDERNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_NUM using the alias name OrderNum.
     * @param value value to set the ORDER_NUM
     */
    public void setOrderNum(Integer value) {
        setAttributeInternal(ORDERNUM, value);
    }

    /**
     * Gets the attribute value for INT_SEQ using the alias name IntSeq.
     * @return the INT_SEQ
     */
    public Long getIntSeq() {
        return (Long) getAttributeInternal(INTSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for INT_SEQ using the alias name IntSeq.
     * @param value value to set the INT_SEQ
     */
    public void setIntSeq(Long value) {
        setAttributeInternal(INTSEQ, value);
    }

    /**
     * Gets the attribute value for LAST_CHANGE using the alias name LastChange.
     * @return the LAST_CHANGE
     */
    public Timestamp getLastChange() {
        return (Timestamp) getAttributeInternal(LASTCHANGE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_CHANGE using the alias name LastChange.
     * @param value value to set the LAST_CHANGE
     */
    public void setLastChange(Timestamp value) {
        setAttributeInternal(LASTCHANGE, value);
    }

    /**
     * Gets the attribute value for TRACK_NAME using the alias name TrackName.
     * @return the TRACK_NAME
     */
    public String getTrackName() {
        return (String) getAttributeInternal(TRACKNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TRACK_NAME using the alias name TrackName.
     * @param value value to set the TRACK_NAME
     */
    public void setTrackName(String value) {
        setAttributeInternal(TRACKNAME, value);
    }

    /**
     * Gets the attribute value for ALBUM using the alias name Album.
     * @return the ALBUM
     */
    public String getAlbum() {
        return (String) getAttributeInternal(ALBUM);
    }

    /**
     * Sets <code>value</code> as attribute value for ALBUM using the alias name Album.
     * @param value value to set the ALBUM
     */
    public void setAlbum(String value) {
        setAttributeInternal(ALBUM, value);
    }

    /**
     * Gets the attribute value for ARTIST using the alias name Artist.
     * @return the ARTIST
     */
    public String getArtist() {
        return (String) getAttributeInternal(ARTIST);
    }

    /**
     * Sets <code>value</code> as attribute value for ARTIST using the alias name Artist.
     * @param value value to set the ARTIST
     */
    public void setArtist(String value) {
        setAttributeInternal(ARTIST, value);
    }

    /**
     * Gets the attribute value for ARTIST_ID using the alias name ArtistId.
     * @return the ARTIST_ID
     */
    public String getArtistId() {
        return (String) getAttributeInternal(ARTISTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ARTIST_ID using the alias name ArtistId.
     * @param value value to set the ARTIST_ID
     */
    public void setArtistId(String value) {
        setAttributeInternal(ARTISTID, value);
    }

    /**
     * Gets the attribute value for ALBUM_ID using the alias name AlbumId.
     * @return the ALBUM_ID
     */
    public String getAlbumId() {
        return (String) getAttributeInternal(ALBUMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ALBUM_ID using the alias name AlbumId.
     * @param value value to set the ALBUM_ID
     */
    public void setAlbumId(String value) {
        setAttributeInternal(ALBUMID, value);
    }

    /**
     * Gets the attribute value for TRACK_ID using the alias name TrackId.
     * @return the TRACK_ID
     */
    public String getTrackId() {
        return (String) getAttributeInternal(TRACKID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRACK_ID using the alias name TrackId.
     * @param value value to set the TRACK_ID
     */
    public void setTrackId(String value) {
        setAttributeInternal(TRACKID, value);
    }

    /**
     * Gets the attribute value for GENRE using the alias name Genre.
     * @return the GENRE
     */
    public String getGenre() {
        return (String) getAttributeInternal(GENRE);
    }

    /**
     * Sets <code>value</code> as attribute value for GENRE using the alias name Genre.
     * @param value value to set the GENRE
     */
    public void setGenre(String value) {
        setAttributeInternal(GENRE, value);
    }

    /**
     * Gets the attribute value for IMAGE_URL using the alias name ImageUrl.
     * @return the IMAGE_URL
     */
    public String getImageUrl() {
        return (String) getAttributeInternal(IMAGEURL);
    }

    /**
     * Sets <code>value</code> as attribute value for IMAGE_URL using the alias name ImageUrl.
     * @param value value to set the IMAGE_URL
     */
    public void setImageUrl(String value) {
        setAttributeInternal(IMAGEURL, value);
    }
}

