package de.adfprojectsesions.hf.model.adfbc.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 22 21:44:58 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HfPlaylistPosViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HfPlaylistPosViewImpl() {
    }
}

