package de.adfprojectsesions.hf.model.adfbc.views;

import de.adfprojectsesions.hf.model.adfbc.views.common.HfPlaylistView;
import de.adfprojectsesions.hf.model.adfbc.views.utils.AdfProjectSessionsBaseViewImpl;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.ViewCriteria;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 10 17:28:12 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HfPlaylistViewImpl extends AdfProjectSessionsBaseViewImpl implements HfPlaylistView {
    private static ADFLogger _logger = ADFLogger.createADFLogger(HfPlaylistViewImpl.class);
    /**
     * This is the default constructor (do not remove).
     */
    public HfPlaylistViewImpl() {
    }

    /**
     * Returns the variable value for bindSearchTerm.
     * @return variable value for bindSearchTerm
     */
    public String getbindSearchTerm() {
        return (String) ensureVariableManager().getVariableValue("bindSearchTerm");
    }

    /**
     * Sets <code>value</code> for variable bindSearchTerm.
     * @param value value to bind as bindSearchTerm
     */
    public void setbindSearchTerm(String value) {
        ensureVariableManager().setVariableValue("bindSearchTerm", value);
    }

    /**
     * Returns the variable value for bindUserId.
     * @return variable value for bindUserId
     */
    public Long getbindUserId() {
        return (Long) ensureVariableManager().getVariableValue("bindUserId");
    }

    /**
     * Sets <code>value</code> for variable bindUserId.
     * @param value value to bind as bindUserId
     */
    public void setbindUserId(Long value) {
        ensureVariableManager().setVariableValue("bindUserId", value);
    }
    
    /**
     * Suchen von Kategorien nach suchstring und user
     * @param searchTerm sollte im Namen oder der Beschreibung enthalten sein
     * @param userId Kategorien des users mit der Id suchen
     */
    public void searchDescriptionByUserId(String searchTerm, Long userId){
        _logger.info("searchDescriptionByUserId " + searchTerm + " " + userId);
        // alte mögliche where clause löschen
        this.setWhereClauseParams(null);
        this.setWhereClause(null);
        // viewCriteria holen und setzten
        ViewCriteria vco = this.getViewCriteria("PlaylistByNameOrDescriptionVC");
        removeApplyViewCriteriaName(vco.getName());
        this.applyViewCriteria(vco);
        this.setbindUserId(userId);
        this.setbindSearchTerm(searchTerm);
        this.executeQuery();
    }
    


    @Override
    public void executeQuery() {
        dumpQueryAndParameters(_logger);
        super.executeQuery();
    }
}

