package de.adfprojectsesions.hf.model.adfbc.views;

import de.adfprojectsesions.hf.model.adfbc.views.common.HfSharedPlaylistView;
import de.adfprojectsesions.hf.model.adfbc.views.utils.AdfProjectSessionsBaseViewImpl;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.ViewCriteria;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 13 20:56:53 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HfSharedPlaylistViewImpl extends AdfProjectSessionsBaseViewImpl implements HfSharedPlaylistView {
    private static ADFLogger _logger = ADFLogger.createADFLogger(HfSharedPlaylistViewImpl.class);
    
    /**
     * This is the default constructor (do not remove).
     */
    public HfSharedPlaylistViewImpl() {
    }

    /**
     * Returns the variable value for bindSearchTerm.
     * @return variable value for bindSearchTerm
     */
    public String getbindSearchTerm() {
        return (String) ensureVariableManager().getVariableValue("bindSearchTerm");
    }

    /**
     * Sets <code>value</code> for variable bindSearchTerm.
     * @param value value to bind as bindSearchTerm
     */
    public void setbindSearchTerm(String value) {
        ensureVariableManager().setVariableValue("bindSearchTerm", value);
    }
    
    /**
     * Suchen von Kategorien nach suchstring.
     * @param searchTerm sollte im Namen oder der Beschreibung enthalten sein
     */
    public void searchDescriptionByUserId(String searchTerm){
        _logger.info("searchDescriptionByUserId " + searchTerm);
        // alte mögliche where clause löschen
        this.setWhereClauseParams(null);
        this.setWhereClause(null);
        // viewCriteria holen und setzten
        ViewCriteria vco = this.getViewCriteria("SharedPlaylistByNameOrDescriptionVC");
        removeApplyViewCriteriaName(vco.getName());
        this.applyViewCriteria(vco);
        this.setbindSearchTerm(searchTerm);
        this.executeQuery();
    }

    @Override
    public void executeQuery() {
        dumpQueryAndParameters(_logger);
        super.executeQuery();
    }
}

