package de.adfprojectsesions.hf.model.adfbc.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 03 18:48:59 CET 2017
// ---------------------------------------------------------------------
public interface HfCatView extends ViewObject {
    void searchDescriptionByUserId(String searchTerm, Long userId);
}

