package de.adfprojectsesions.hf.model.adfbc.views.common;

import java.sql.Timestamp;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 22 21:46:49 CET 2017
// ---------------------------------------------------------------------
public interface HfPlaylistPosViewRow extends Row {
    String getAlbum();

    String getAlbumId();

    String getArtist();

    String getArtistId();

    String getGenre();

    Long getHfPlaylistIk();

    String getImageUrl();

    Long getIntKey();

    Long getIntSeq();

    Timestamp getLastChange();

    Integer getOrderNum();

    String getTrackId();

    String getTrackName();

    void setAlbum(String value);

    void setAlbumId(String value);

    void setArtist(String value);

    void setArtistId(String value);

    void setGenre(String value);

    void setHfPlaylistIk(Long value);

    void setImageUrl(String value);

    void setIntKey(Long value);

    void setIntSeq(Long value);

    void setLastChange(Timestamp value);

    void setOrderNum(Integer value);

    void setTrackId(String value);

    void setTrackName(String value);
}

