package de.adfprojectsesions.hf.model.adfbc.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 10 17:29:39 CET 2017
// ---------------------------------------------------------------------
public interface HfPlaylistView extends ViewObject {
    void searchDescriptionByUserId(String searchTerm, Long userId);
}

