package de.adfprojectsesions.hf.model.adfbc.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 13 20:59:21 CET 2017
// ---------------------------------------------------------------------
public interface HFSharedPlaylistView extends ViewObject {
    void searchDescriptionByUserId(String searchTerm);
}

