--------------------------------------------------------
--  Datei erstellt -Montag-März-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HF_CAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADF_PROJECT_SESSION"."HF_CAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence HF_PLAYLIST_POS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADF_PROJECT_SESSION"."HF_PLAYLIST_POS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence HF_PLAYLIST_RAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence HF_PLAYLIST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADF_PROJECT_SESSION"."HF_PLAYLIST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence HF_USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADF_PROJECT_SESSION"."HF_USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 242337 START WITH 242377 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table HF_CAT
--------------------------------------------------------

  CREATE TABLE "ADF_PROJECT_SESSION"."HF_CAT" 
   (	"INT_KEY" NUMBER(11,0), 
	"HF_USER_IK" NUMBER(11,0), 
	"CAT_NAME" VARCHAR2(255 BYTE), 
	"PARENT_HF_CAT_IK" NUMBER(11,0), 
	"CAT_DESC" VARCHAR2(2000 BYTE), 
	"INT_SEQ" NUMBER(10,0), 
	"LAST_CHANGE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HF_META_DATA
--------------------------------------------------------

  CREATE TABLE "ADF_PROJECT_SESSION"."HF_META_DATA" 
   (	"INT_KEY" NUMBER(11,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"KEY" VARCHAR2(2000 BYTE), 
	"VALUE" VARCHAR2(2000 BYTE), 
	"NUM_VALUE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HF_PLAYLIST
--------------------------------------------------------

  CREATE TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST" 
   (	"INT_KEY" NUMBER(11,0), 
	"PLAYLIST_NAME" VARCHAR2(255 BYTE), 
	"HF_CAT_IK" NUMBER(11,0), 
	"HF_USER_IK" NUMBER(11,0), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"INT_SEQ" NUMBER(10,0), 
	"LAST_CHANGE" DATE, 
	"SHARE_FLAG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HF_PLAYLIST_POS
--------------------------------------------------------

  CREATE TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_POS" 
   (	"INT_KEY" NUMBER(11,0), 
	"HF_PLAYLIST_IK" NUMBER(11,0), 
	"ORDER_NUM" NUMBER(3,0), 
	"INT_SEQ" NUMBER(10,0), 
	"LAST_CHANGE" DATE, 
	"TRACK_NAME" VARCHAR2(255 BYTE), 
	"ALBUM" VARCHAR2(255 BYTE), 
	"ARTIST" VARCHAR2(255 BYTE), 
	"ARTIST_ID" VARCHAR2(255 BYTE), 
	"ALBUM_ID" VARCHAR2(255 BYTE), 
	"TRACK_ID" VARCHAR2(255 BYTE), 
	"GENRE" VARCHAR2(255 BYTE), 
	"IMAGE_URL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HF_PLAYLIST_RAT
--------------------------------------------------------

  CREATE TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT" 
   (	"INT_KEY" NUMBER(11,0), 
	"RATING" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"HF_PLAYLIST_IK" NUMBER(11,0), 
	"RATER_NAME" VARCHAR2(255 BYTE), 
	"INT_SEQ" NUMBER(10,0), 
	"LAST_CHANGE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HF_USER
--------------------------------------------------------

  CREATE TABLE "ADF_PROJECT_SESSION"."HF_USER" 
   (	"INT_KEY" NUMBER(11,0), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"LONGNAME" VARCHAR2(255 BYTE), 
	"INT_SEQ" NUMBER(10,0), 
	"LAST_CHANGE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADF_PROJECT_SESSION.HF_CAT
SET DEFINE OFF;
Insert into ADF_PROJECT_SESSION.HF_CAT (INT_KEY,HF_USER_IK,CAT_NAME,"parent_hf_cat_ik",CAT_DESC,INT_SEQ,LAST_CHANGE) values ('1','21','Rock',null,'Rock Musik','1',to_date('01.03.17','DD.MM.RR'));
Insert into ADF_PROJECT_SESSION.HF_CAT (INT_KEY,HF_USER_IK,CAT_NAME,"parent_hf_cat_ik",CAT_DESC,INT_SEQ,LAST_CHANGE) values ('21','21','Grunch','1','Grunch Musik','1',to_date('01.03.17','DD.MM.RR'));
Insert into ADF_PROJECT_SESSION.HF_CAT (INT_KEY,HF_USER_IK,CAT_NAME,"parent_hf_cat_ik",CAT_DESC,INT_SEQ,LAST_CHANGE) values ('41','21','Metal','1','Metal Musik','45',to_date('11.03.17','DD.MM.RR'));
Insert into ADF_PROJECT_SESSION.HF_CAT (INT_KEY,HF_USER_IK,CAT_NAME,"parent_hf_cat_ik",CAT_DESC,INT_SEQ,LAST_CHANGE) values ('61','21','Pop',null,'Pop Musik','62',to_date('13.03.17','DD.MM.RR'));
REM INSERTING into ADF_PROJECT_SESSION.HF_META_DATA
SET DEFINE OFF;
REM INSERTING into ADF_PROJECT_SESSION.HF_PLAYLIST
SET DEFINE OFF;
Insert into ADF_PROJECT_SESSION.HF_PLAYLIST (INT_KEY,PLAYLIST_NAME,HF_CAT_IK,HF_USER_IK,DESCRIPTION,INT_SEQ,LAST_CHANGE,SHARE_FLAG) values ('1','PL1','21','21','Test1','2',to_date('11.03.17','DD.MM.RR'),null);
Insert into ADF_PROJECT_SESSION.HF_PLAYLIST (INT_KEY,PLAYLIST_NAME,HF_CAT_IK,HF_USER_IK,DESCRIPTION,INT_SEQ,LAST_CHANGE,SHARE_FLAG) values ('3','PL2','21','21','Test2','4',to_date('11.03.17','DD.MM.RR'),null);
Insert into ADF_PROJECT_SESSION.HF_PLAYLIST (INT_KEY,PLAYLIST_NAME,HF_CAT_IK,HF_USER_IK,DESCRIPTION,INT_SEQ,LAST_CHANGE,SHARE_FLAG) values ('8','PL1','1','21','Playlist 1','9',to_date('11.03.17','DD.MM.RR'),null);
Insert into ADF_PROJECT_SESSION.HF_PLAYLIST (INT_KEY,PLAYLIST_NAME,HF_CAT_IK,HF_USER_IK,DESCRIPTION,INT_SEQ,LAST_CHANGE,SHARE_FLAG) values ('5','PL3','21','21','Test3','7',null,null);
REM INSERTING into ADF_PROJECT_SESSION.HF_PLAYLIST_POS
SET DEFINE OFF;
Insert into ADF_PROJECT_SESSION.HF_PLAYLIST_POS (INT_KEY,HF_PLAYLIST_IK,ORDER_NUM,INT_SEQ,LAST_CHANGE,TRACK_NAME,ALBUM,ARTIST,ARTIST_ID,ALBUM_ID,TRACK_ID,GENRE,IMAGE_URL) values ('1','5','1','2',to_date('11.03.17','DD.MM.RR'),'T1',null,null,null,null,null,null,null);
Insert into ADF_PROJECT_SESSION.HF_PLAYLIST_POS (INT_KEY,HF_PLAYLIST_IK,ORDER_NUM,INT_SEQ,LAST_CHANGE,TRACK_NAME,ALBUM,ARTIST,ARTIST_ID,ALBUM_ID,TRACK_ID,GENRE,IMAGE_URL) values ('3','5','2','4',to_date('11.03.17','DD.MM.RR'),'T2',null,null,null,null,null,null,null);
Insert into ADF_PROJECT_SESSION.HF_PLAYLIST_POS (INT_KEY,HF_PLAYLIST_IK,ORDER_NUM,INT_SEQ,LAST_CHANGE,TRACK_NAME,ALBUM,ARTIST,ARTIST_ID,ALBUM_ID,TRACK_ID,GENRE,IMAGE_URL) values ('5','5','3','6',to_date('11.03.17','DD.MM.RR'),'T3',null,null,null,null,null,null,null);
REM INSERTING into ADF_PROJECT_SESSION.HF_PLAYLIST_RAT
SET DEFINE OFF;
REM INSERTING into ADF_PROJECT_SESSION.HF_USER
SET DEFINE OFF;
Insert into ADF_PROJECT_SESSION.HF_USER (INT_KEY,USERNAME,PASSWORD,LONGNAME,INT_SEQ,LAST_CHANGE) values ('21','wolf','wb','Wolf G. Beckmann','22',null);
Insert into ADF_PROJECT_SESSION.HF_USER (INT_KEY,USERNAME,PASSWORD,LONGNAME,INT_SEQ,LAST_CHANGE) values ('23','timo','th','Timo Hahn','24',null);
--------------------------------------------------------
--  DDL for Index HF_CAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADF_PROJECT_SESSION"."HF_CAT_PK" ON "ADF_PROJECT_SESSION"."HF_CAT" ("INT_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HF_META_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADF_PROJECT_SESSION"."HF_META_DATA_PK" ON "ADF_PROJECT_SESSION"."HF_META_DATA" ("INT_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HF_META_DATA_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADF_PROJECT_SESSION"."HF_META_DATA_UK1" ON "ADF_PROJECT_SESSION"."HF_META_DATA" ("NAME", "KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HF_PLAYLIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADF_PROJECT_SESSION"."HF_PLAYLIST_PK" ON "ADF_PROJECT_SESSION"."HF_PLAYLIST" ("INT_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HF_PLAYLIST_POS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADF_PROJECT_SESSION"."HF_PLAYLIST_POS_PK" ON "ADF_PROJECT_SESSION"."HF_PLAYLIST_POS" ("INT_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HF_PLAYLIST_RAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT_PK" ON "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT" ("INT_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HF_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADF_PROJECT_SESSION"."HF_USER_PK" ON "ADF_PROJECT_SESSION"."HF_USER" ("INT_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HF_USER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HF"."HF_USER_UK1" ON "HF"."HF_USER" ("USERNAME") 
  ;
--------------------------------------------------------
--  Constraints for Table HF_CAT
--------------------------------------------------------

  ALTER TABLE "ADF_PROJECT_SESSION"."HF_CAT" MODIFY ("HF_USER_IK" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_CAT" MODIFY ("CAT_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_CAT" MODIFY ("INT_KEY" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_CAT" ADD CONSTRAINT "HF_CAT_PK" PRIMARY KEY ("INT_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HF_META_DATA
--------------------------------------------------------

  ALTER TABLE "ADF_PROJECT_SESSION"."HF_META_DATA" MODIFY ("INT_KEY" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_META_DATA" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_META_DATA" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_META_DATA" ADD CONSTRAINT "HF_META_DATA_PK" PRIMARY KEY ("INT_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_META_DATA" ADD CONSTRAINT "HF_META_DATA_UK1" UNIQUE ("NAME", "KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HF_PLAYLIST
--------------------------------------------------------

  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST" MODIFY ("PLAYLIST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST" MODIFY ("HF_CAT_IK" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST" MODIFY ("HF_USER_IK" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST" MODIFY ("INT_KEY" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST" ADD CONSTRAINT "HF_PLAYLIST_PK" PRIMARY KEY ("INT_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HF_PLAYLIST_POS
--------------------------------------------------------

  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_POS" MODIFY ("HF_PLAYLIST_IK" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_POS" MODIFY ("INT_KEY" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_POS" ADD CONSTRAINT "HF_PLAYLIST_POS_PK" PRIMARY KEY ("INT_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HF_PLAYLIST_RAT
--------------------------------------------------------

  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT" MODIFY ("HF_PLAYLIST_IK" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT" MODIFY ("INT_KEY" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT" ADD CONSTRAINT "HF_PLAYLIST_RAT_PK" PRIMARY KEY ("INT_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HF_USER
--------------------------------------------------------

  ALTER TABLE "ADF_PROJECT_SESSION"."HF_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_USER" MODIFY ("LONGNAME" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_USER" MODIFY ("INT_KEY" NOT NULL ENABLE);
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_USER" ADD CONSTRAINT "HF_USER_PK" PRIMARY KEY ("INT_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HF"."HF_USER" ADD CONSTRAINT "HF_USER_UK1" UNIQUE ("USERNAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HF_CAT
--------------------------------------------------------

  ALTER TABLE "ADF_PROJECT_SESSION"."HF_CAT" ADD CONSTRAINT "HF_CAT_HF_CAT_FK1" FOREIGN KEY ("parent_hf_cat_ik")
	  REFERENCES "ADF_PROJECT_SESSION"."HF_CAT" ("INT_KEY") ENABLE;
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_CAT" ADD CONSTRAINT "HF_CAT_HF_USER_FK1" FOREIGN KEY ("HF_USER_IK")
	  REFERENCES "ADF_PROJECT_SESSION"."HF_USER" ("INT_KEY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HF_PLAYLIST
--------------------------------------------------------

  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST" ADD CONSTRAINT "HF_PLAYLIST_HF_CAT_FK1" FOREIGN KEY ("HF_CAT_IK")
	  REFERENCES "ADF_PROJECT_SESSION"."HF_CAT" ("INT_KEY") ENABLE;
  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST" ADD CONSTRAINT "HF_PLAYLIST_HF_USER_FK1" FOREIGN KEY ("HF_USER_IK")
	  REFERENCES "ADF_PROJECT_SESSION"."HF_USER" ("INT_KEY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HF_PLAYLIST_POS
--------------------------------------------------------

  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_POS" ADD CONSTRAINT "HF_PLAYLIST_POS_FK1" FOREIGN KEY ("HF_PLAYLIST_IK")
	  REFERENCES "ADF_PROJECT_SESSION"."HF_PLAYLIST" ("INT_KEY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HF_PLAYLIST_RAT
--------------------------------------------------------

  ALTER TABLE "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT" ADD CONSTRAINT "HF_PLAYLIST_RAT_FK1" FOREIGN KEY ("HF_PLAYLIST_IK")
	  REFERENCES "ADF_PROJECT_SESSION"."HF_PLAYLIST" ("INT_KEY") ENABLE;
--------------------------------------------------------
--  DDL for Trigger HF_CAT_TRIG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADF_PROJECT_SESSION"."HF_CAT_TRIG" 
BEFORE INSERT or update  ON hf_cat FOR EACH ROW
BEGIN
 IF :NEW.int_key IS NULL OR :NEW.int_key < 0 THEN
   SELECT hf_cat_seq.NEXTVAL,sysdate
     INTO :NEW.int_key,:NEW.LAST_CHANGE
     FROM DUAL;
   END IF;
   

   SELECT hf_cat_seq.NEXTVAL
     INTO :NEW.int_seq
     FROM DUAL;

END;
/
ALTER TRIGGER "ADF_PROJECT_SESSION"."HF_CAT_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HF_PLAYLIST_POS_TRIG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADF_PROJECT_SESSION"."HF_PLAYLIST_POS_TRIG" 
BEFORE INSERT or update  ON hf_playlist_pos FOR EACH ROW
BEGIN
 IF :NEW.int_key IS NULL OR :NEW.int_key < 0 THEN
   SELECT hf_playlist_pos_seq.NEXTVAL,sysdate
     INTO :NEW.int_key,:NEW.LAST_CHANGE
     FROM DUAL;
   END IF;
   

   SELECT hf_playlist_pos_seq.NEXTVAL
     INTO :NEW.int_seq
     FROM DUAL;

END;
/
ALTER TRIGGER "ADF_PROJECT_SESSION"."HF_PLAYLIST_POS_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HF_PLAYLIST_RAT_TRIG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT_TRIG" 
BEFORE INSERT or update  ON hf_playlist_rat FOR EACH ROW
BEGIN
 IF :NEW.int_key IS NULL OR :NEW.int_key < 0 THEN
   SELECT hf_playlist_rat_seq.NEXTVAL,sysdate
     INTO :NEW.int_key,:NEW.LAST_CHANGE
     FROM DUAL;
   END IF;
   

   SELECT hf_playlist_rat_seq.NEXTVAL
     INTO :NEW.int_seq
     FROM DUAL;

END;
/
ALTER TRIGGER "ADF_PROJECT_SESSION"."HF_PLAYLIST_RAT_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HF_PLAYLIST_TRIG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADF_PROJECT_SESSION"."HF_PLAYLIST_TRIG" 
BEFORE INSERT or update  ON hf_playlist FOR EACH ROW
BEGIN
 IF :NEW.int_key IS NULL OR :NEW.int_key < 0 THEN
   SELECT hf_playlist_seq.NEXTVAL,sysdate
     INTO :NEW.int_key,:NEW.LAST_CHANGE
     FROM DUAL;
   END IF;
   

   SELECT hf_playlist_seq.NEXTVAL
     INTO :NEW.int_seq
     FROM DUAL;

END;
/
ALTER TRIGGER "ADF_PROJECT_SESSION"."HF_PLAYLIST_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HF_USER_TRIG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADF_PROJECT_SESSION"."HF_USER_TRIG" 
BEFORE INSERT or update ON hf_user FOR EACH ROW
BEGIN
 IF :NEW.int_key IS NULL OR :NEW.int_key < 0 THEN
   SELECT hf_user_seq.NEXTVAL+round(SYS.DBMS_RANDOM.value(0,90000)),sysdate
     INTO :NEW.int_key,:NEW.LAST_CHANGE
     FROM DUAL;
   END IF;
   
   SELECT hf_user_seq.NEXTVAL
     INTO :NEW.int_seq
     FROM DUAL;

   
END;
/
ALTER TRIGGER "ADF_PROJECT_SESSION"."HF_USER_TRIG" ENABLE;
