package oracle.apps.uikit;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 21 17:10:15 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for UsersView1.
     * @return UsersView1
     */
    public ViewObjectImpl getUsersView1() {
        return (ViewObjectImpl) findViewObject("UsersView1");
    }
    
    /*
     * 
     * 
     **/
    public UserInfo Login(String UserLastName,String  password){
        
        UserInfo user= null;
        ViewObject vo =  getUsersView1();
        ViewCriteria vc = vo.createViewCriteria();
        ViewCriteriaRow vcr =vc.createViewCriteriaRow();
        
        vcr.setAttribute("Lastname", UserLastName);
        vcr.setAttribute("Userpwd", password);
               
        vc.add(vcr);
        vo.applyViewCriteria(vc);
        vo.executeQuery();
        
        if (vo.hasNext())
        {
            user= new UserInfo();
            Row row=vo.next(); 
            user.setUserId(((Number)row.getAttribute("Userid")).intValue());
            user.setFirstName ((String)row.getAttribute("Firstname"));
            user.setLastName ((String)row.getAttribute("Lastname"));
            user.setPassword  ((String)row.getAttribute("Userpwd"));
            
              
        }
        return user;
        }
}

