package de.adfprojectsesions.hf.model.adfbc.service;

import de.adfprojectsesions.hf.model.adfbc.service.common.HFAppModule;

import java.sql.SQLException;

import java.sql.Statement;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 15:35:42 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HFAppModuleImpl extends ApplicationModuleImpl implements HFAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HFAppModuleImpl() {
    }

    /**
     * Container's getter for HfCatView.
     * @return HfCatView
     */
    public ViewObjectImpl getHfCatView() {
        return (ViewObjectImpl) findViewObject("HfCatView");
    }

    /**
     * Container's getter for HfPlaylistPosView.
     * @return HfPlaylistPosView
     */
    public ViewObjectImpl getHfPlaylistPosView() {
        return (ViewObjectImpl) findViewObject("HfPlaylistPosView");
    }

    /**
     * Container's getter for HfPlaylistRatView.
     * @return HfPlaylistRatView
     */
    public ViewObjectImpl getHfPlaylistRatView() {
        return (ViewObjectImpl) findViewObject("HfPlaylistRatView");
    }

    /**
     * Container's getter for HfPlaylistView.
     * @return HfPlaylistView
     */
    public ViewObjectImpl getHfPlaylistView() {
        return (ViewObjectImpl) findViewObject("HfPlaylistView");
    }

    /**
     * Container's getter for HfUserView.
     * @return HfUserView
     */
    public ViewObjectImpl getHfUserView() {
        return (ViewObjectImpl) findViewObject("HfUserView");
    }

    /**
     * Container's getter for HfPlaylistOfCatView.
     * @return HfPlaylistOfCatView
     */
    public ViewObjectImpl getHfPlaylistOfCatView() {
        return (ViewObjectImpl) findViewObject("HfPlaylistOfCatView");
    }

    /**
     * Container's getter for HfPlaylistPosOfPlaylistView.
     * @return HfPlaylistPosOfPlaylistView
     */
    public ViewObjectImpl getHfPlaylistPosOfPlaylistView() {
        return (ViewObjectImpl) findViewObject("HfPlaylistPosOfPlaylistView");
    }

    /**
     * Container's getter for HfPlaylistRatOfPlaylistView.
     * @return HfPlaylistRatOfPlaylistView
     */
    public ViewObjectImpl getHfPlaylistRatOfPlaylistView() {
        return (ViewObjectImpl) findViewObject("HfPlaylistRatOfPlaylistView");
    }

    /**
     * Container's getter for HfPlaylistOfUserView.
     * @return HfPlaylistOfUserView
     */
    public ViewObjectImpl getHfPlaylistOfUserView() {
        return (ViewObjectImpl) findViewObject("HfPlaylistOfUserView");
    }

    /**
     * Container's getter for HfCatOfUserView.
     * @return HfCatOfUserView
     */
    public ViewObjectImpl getHfCatOfUserView() {
        return (ViewObjectImpl) findViewObject("HfCatOfUserView");
    }

    /**
     * Container's getter for HfUserLoginView.
     * @return HfUserLoginView
     */
    public ViewObjectImpl getHfUserLoginView() {
        return (ViewObjectImpl) findViewObject("HfUserLoginView");
    }

    /**
     * Container's getter for HfPlaylistHfCatFk1Link1.
     * @return HfPlaylistHfCatFk1Link1
     */
    public ViewLinkImpl getHfPlaylistHfCatFk1Link1() {
        return (ViewLinkImpl) findViewLink("HfPlaylistHfCatFk1Link1");
    }

    /**
     * Container's getter for HfPlaylistPosFk1Link1.
     * @return HfPlaylistPosFk1Link1
     */
    public ViewLinkImpl getHfPlaylistPosFk1Link1() {
        return (ViewLinkImpl) findViewLink("HfPlaylistPosFk1Link1");
    }

    /**
     * Container's getter for HfPlaylistRatFk1Link1.
     * @return HfPlaylistRatFk1Link1
     */
    public ViewLinkImpl getHfPlaylistRatFk1Link1() {
        return (ViewLinkImpl) findViewLink("HfPlaylistRatFk1Link1");
    }

    /**
     * Container's getter for HfPlaylistHfUserFk1Link1.
     * @return HfPlaylistHfUserFk1Link1
     */
    public ViewLinkImpl getHfPlaylistHfUserFk1Link1() {
        return (ViewLinkImpl) findViewLink("HfPlaylistHfUserFk1Link1");
    }

    /**
     * Container's getter for HfCatHfUserFk1Link1.
     * @return HfCatHfUserFk1Link1
     */
    public ViewLinkImpl getHfCatHfUserFk1Link1() {
        return (ViewLinkImpl) findViewLink("HfCatHfUserFk1Link1");
    }

    public void registerUser(Integer key, String username, String longname, String password) {

        String strQuery =
            "insert into HF_USER (INT_KEY,USERNAME,LONGNAME,PASSWORD) VALUES('"+key+"','"+username+"','"+longname+"','"+password+"')";

        DBTransaction dbTransaction = this.getDBTransaction();

        Statement stmt = dbTransaction.createStatement(1);

        int result = 0;

        try {

            result = stmt.executeUpdate(strQuery);
            dbTransaction.commit();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

