package de.adfprojectsesions.hf.model.adfbc.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 15:51:14 CET 2017
// ---------------------------------------------------------------------
public interface HFAppModule extends ApplicationModule {
    void registerUser(Integer key, String username, String longname, String password);
}

